---
# tasks file for server_patching

- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    file: "{{ item.repo_file }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
  loop: repositories

- name: install packages
  yum: 
    name: "{{ item.package_name }}"
    state: "{{ item.package_version }}"
  loop: packages
...
